### ISSUE TITLE
The Cyclone statement

### ISSUE THREAD

**Issue by edfrias** [codedex-io/python-101#23]
Hi everyone! Sorry in advance if this issue does not have any proper format, I haven't seen any rules to open an issue.

I've been doing the python course, **so far its being great!**, I've realised that there's a new exercise, the cyclone, and by reading the statement I've noticed something that could might be an issue. As said in the exercise:

> - If their height is greater than or equal to 137 and their credit is greater than or equal to 10, print "Enjoy the ride!" 
> - If their height is **less than 200**, check the following:

2 meters is too much isn't it? I was thinking that maybe this was a mistake as the next statement say something like ` if their height is less than 100 or they are not with_taller_person`

Is 200 cms right? If so, I supose everyone is giant in Coney Island! :D

Cheers!

**Comment by Dusch4593** [comment]
Hi @edfrias! I help oversee the curriculum content at Codédex. 😄

Thank you for flagging this! It should have said `137` instead of `200`; we went ahead and updated the site.

I'm going to close this issue for now but feel free to check out [the challenge](https://github.com/codedex-io/curriculum/pull/59/files) to see if everything looks ok.

Please let us know how else we can improve our content and feel free to create another issue. 😄

**Comment by edfrias** [comment]
Thank you so much @Dusch4593
